export AWS_CONFIG_PATH=~/Documents/Software/AWS/Amazon_AWS_DDNS_Client/config/
export HEALTHCHECK_HEARTBEAT_FILE=~/Documents/Software/AWS/Amazon_AWS_DDNS_Client/config/heartbeat
export HEALTHCHECK_INTERVAL_FILE=~/Documents/Software/AWS/Amazon_AWS_DDNS_Client/config/max_age
export AWS_ACCESS_KEY_ID=AAAAAAAAAAAAAAAAAAAAAAAAA
export AWS_SECRET_ACCESS_KEY=BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
export AWS_PROFILE=route53_user_env
export AWS_SHARED_CREDENTIALS_FILE=~/Documents/Software/AWS/Amazon_AWS_DDNS_Client

export AWS_ACCESS_KEY_ID_FILE=~/Documents/Software/AWS/Amazon_AWS_DDNS_Client/config/secret_aws_access_key_id
export AWS_SECRET_ACCESS_KEY_FILE=~/Documents/Software/AWS/Amazon_AWS_DDNS_Client/config/secret_aws_secret_access_key

unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_PROFILE
